# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2211cc4f1b9c6444f595f03ad1d36707dfa38c95337066b4fe8521f2049540b57f7160b6bc6823df1ab06a293ce76843fa9bf377ebc43002bcaec0944746379

test:
  secret_key_base: a7597ea03dccfe4247d7182e9cee41e5df7ea85b63f5f56e21b66d1b017900358a27214f01a95aff57f5f52ed1bed1004a877eaac02e2a132dbef1ac579296d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
